### ISSUE TITLE
 Crash before start

### ISSUE THREAD

**Issue by kotmatross28729** [FalsePattern/Triangulator#35]
It doesn't give me a crashlog, but just a log

**Mixin config mixins.triangulator.json requires mixin subsystem version 0.8.3 but 0.7.11 was found. The mixin config will not be applied.**
      I don't know what it is, but it means something

Log:

[00:03:32] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[00:03:32] [main/INFO]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[00:03:32] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[00:03:32] [main/INFO]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
[00:03:32] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_341, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_341
[00:03:32] [main/INFO]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.7.10_HD_U_E7.jar
[00:03:32] [main/INFO]: Initializing SpongeMixinsCore
[00:03:32] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/1/AppData/Roaming/.minecraft/mods/SpongeMixins-1.2.0.jar Service=LaunchWrapper Env=CLIENT
[00:03:32] [main/DEBUG]: Instantiating coremod class SpongeMixinsCore
[00:03:32] [main/TRACE]: coremod named SpongeMixin Core Plugin is loading
[00:03:32] [main/DEBUG]: The coremod ru.timeconqueror.spongemixins.core.SpongeMixinsCore requested minecraft version 1.7.10 and minecraft is 1.7.10. It will be loaded.
[00:03:32] [main/DEBUG]: Enqueued coremod SpongeMixin Core Plugin
[00:03:32] [main/TRACE]: coremod named SpongeMixin Core Plugin is loading
[00:03:32] [main/DEBUG]: The coremod ru.timeconqueror.spongemixins.core.SpongeMixinsCore requested minecraft version 1.7.10 and minecraft is 1.7.10. It will be loaded.
[00:03:32] [main/DEBUG]: Enqueued coremod SpongeMixin Core Plugin
[00:03:32] [main/DEBUG]: Examining for coremod candidacy triangulator-mc1.7.10-2.0.0-alpha0001.jar
[00:03:32] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from triangulator-mc1.7.10-2.0.0-alpha0001.jar
[00:03:32] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[00:03:32] [main/INFO]: Loading tweak class name optifine.OptiFineForgeTweaker
[00:03:32] [main/INFO]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[00:03:32] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[00:03:32] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[00:03:32] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[00:03:32] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[00:03:32] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[00:03:32] [main/DEBUG]: Injecting coremod SpongeMixin Core Plugin {ru.timeconqueror.spongemixins.core.SpongeMixinsCore} class transformers
[00:03:32] [main/DEBUG]: Injection complete
[00:03:32] [main/DEBUG]: Running coremod plugin for SpongeMixin Core Plugin {ru.timeconqueror.spongemixins.core.SpongeMixinsCore}
[00:03:32] [main/DEBUG]: Running coremod plugin SpongeMixin Core Plugin
[00:03:32] [main/DEBUG]: Coremod plugin class SpongeMixinsCore run successfully
[00:03:32] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[00:03:32] [main/DEBUG]: Injecting coremod SpongeMixin Core Plugin {ru.timeconqueror.spongemixins.core.SpongeMixinsCore} class transformers
[00:03:32] [main/DEBUG]: Injection complete
[00:03:32] [main/DEBUG]: Running coremod plugin for SpongeMixin Core Plugin {ru.timeconqueror.spongemixins.core.SpongeMixinsCore}
[00:03:32] [main/DEBUG]: Running coremod plugin SpongeMixin Core Plugin
[00:03:32] [main/DEBUG]: Coremod plugin class SpongeMixinsCore run successfully
[00:03:32] [main/INFO]: Calling tweak class optifine.OptiFineForgeTweaker
[00:03:32] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[00:03:32] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[00:03:32] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ClassTransformer
[00:03:32] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ZIP file: C:\Users\1\AppData\Roaming.minecraft\mods\OptiFine_1.7.10_HD_U_E7.jar
[00:03:32] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[00:03:32] [main/DEBUG]: Injecting coremod FMLCorePlugin {cpw.mods.fml.relauncher.FMLCorePlugin} class transformers
[00:03:32] [main/TRACE]: Registering transformer cpw.mods.fml.common.asm.transformers.MarkerTransformer
[00:03:32] [main/TRACE]: Registering transformer cpw.mods.fml.common.asm.transformers.SideTransformer
[00:03:32] [main/TRACE]: Registering transformer cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
[00:03:32] [main/DEBUG]: Injection complete
[00:03:32] [main/DEBUG]: Running coremod plugin for FMLCorePlugin {cpw.mods.fml.relauncher.FMLCorePlugin}
[00:03:32] [main/DEBUG]: Running coremod plugin FMLCorePlugin
[00:03:33] [main/DEBUG]: Read 527 binary patches
[00:03:34] [main/INFO]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[00:03:34] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[00:03:34] [main/DEBUG]: Coremod plugin class FMLCorePlugin run successfully
[00:03:34] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[00:03:34] [main/DEBUG]: Injecting coremod FMLForgePlugin {net.minecraftforge.classloading.FMLForgePlugin} class transformers
[00:03:34] [main/TRACE]: Registering transformer net.minecraftforge.classloading.FluidIdTransformer
[00:03:34] [main/DEBUG]: Injection complete
[00:03:34] [main/DEBUG]: Running coremod plugin for FMLForgePlugin {net.minecraftforge.classloading.FMLForgePlugin}
[00:03:34] [main/DEBUG]: Running coremod plugin FMLForgePlugin
[00:03:34] [main/DEBUG]: Coremod plugin class FMLForgePlugin run successfully
[00:03:34] [main/INFO]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[00:03:34] [main/INFO]: Initialised Mixin FML Remapper Adapter with cpw.mods.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@52d239ba
[00:03:34] [main/DEBUG]: Instantiating coremod class CoreLoadingPlugin
[00:03:34] [main/WARN]: The coremod com.falsepattern.triangulator.CoreLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[00:03:34] [main/DEBUG]: Enqueued coremod CoreLoadingPlugin
[00:03:34] [main/INFO]: Compatibility level set to JAVA_8
[00:03:34] [main/WARN]: Mixin config mixins.triangulator.json requires mixin subsystem version 0.8.3 but 0.7.11 was found. The mixin config will not be applied.
Exception in thread "main" [00:03:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: org.spongepowered.asm.launch.MixinInitialisationError: Required mixin config mixins.triangulator.json requires mixin subsystem version 0.8.3
[00:03:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at org.spongepowered.asm.mixin.transformer.MixinConfig.checkVersion(MixinConfig.java:417)
[00:03:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:331)
[00:03:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:894)
[00:03:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:116)
[00:03:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:91)
[00:03:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:78)
[00:03:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at org.spongepowered.asm.launch.platform.MixinPlatformManager.addConfig(MixinPlatformManager.java:282)
[00:03:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at org.spongepowered.asm.launch.platform.MixinPlatformAgentDefault.prepare(MixinPlatformAgentDefault.java:56)
[00:03:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at org.spongepowered.asm.launch.platform.MixinContainer.prepare(MixinContainer.java:103)
[00:03:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at org.spongepowered.asm.launch.platform.MixinPlatformManager.addContainer(MixinPlatformManager.java:146)
[00:03:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at org.spongepowered.asm.launch.platform.MixinPlatformManager.scanClasspath(MixinPlatformManager.java:230)
[00:03:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:199)
[00:03:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at org.spongepowered.asm.mixin.EnvironmentStateTweaker.injectIntoClassLoader(EnvironmentStateTweaker.java:48)
[00:03:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[00:03:34] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
`

**Comment by kotmatross28729** [comment]
I'm sorry. I'm dumb, I had to install a gas station
